version: "3"

services:
  nadoharu-front:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_GRAPHQL_API=${NEXT_PUBLIC_GRAPHQL_API}
    environment:
      - NEXT_PUBLIC_GRAPHQL_API=${NEXT_PUBLIC_GRAPHQL_API}
      - COOKIE_PASSWORD=${COOKIE_PASSWORD}
      - NODE_ENV=production
    ports:
      - "3000:3000"
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3000",
        ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
